FROM node:14-alpine3.10 AS web
WORKDIR /app
COPY ./package.json ./yarn.lock ./
RUN yarn install
ADD . /app
RUN yarn classic

RUN echo '$(function () {' > packages/classic/php/js/app.js
RUN cat packages/classic/dist/js/app.js >> packages/classic/php/js/app.js
RUN echo "});" >> packages/classic/php/js/app.js

FROM owncloud/server:10.7
COPY --from=web /app/packages/classic/php /var/www/owncloud/apps/rds