FROM node:14-buster AS api-builder
WORKDIR /srv
COPY dev/describo-online/ui/ /srv/
COPY dev/describo-ui-plugins/ /plugins/
RUN npm install
RUN npm run build

FROM nginx:latest   
COPY --from=api-builder /srv/dist/ /usr/share/nginx/html
