FROM node:14-alpine3.10 AS web
WORKDIR /app
RUN apk add gettext
COPY ./package.json ./yarn.lock ./
RUN yarn install
COPY . .
RUN yarn web

FROM nginx
COPY --from=web /app/packages/web/dist /usr/share/nginx/html
