FROM node:14-alpine3.10 AS web
WORKDIR /app
COPY ./package.json ./yarn.lock ./
RUN yarn install
ADD . /app
RUN yarn web

FROM nginx:latest
COPY --from=web /app/packages/web/dist /usr/share/nginx/html
