FROM zivgitlab.uni-muenster.de/sciebo-rds/dependency_proxy/containers/rust:1.53 as builder

WORKDIR /app
RUN mkdir src && echo "// dummy file" > ./src/lib.rs
COPY Cargo.lock Cargo.toml ./

RUN cargo install --path .

FROM zivgitlab.uni-muenster.de/sciebo-rds/dependency_proxy/containers/debian:buster-slim

RUN apt-get update && apt install -y openssl && apt-get clean autoclean && apt-get autoremove --yes && rm -rf /var/lib/{apt,dpkg,cache,log}/
COPY --from=builder /usr/local/cargo/bin/helper /usr/local/bin/helper
COPY . .

CMD ["helper"]
