FROM rust:1.53 as builder

WORKDIR /app
COPY . .

RUN cargo install --path .

FROM debian:buster-slim

RUN apt-get update && apt install -y openssl rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/helper /usr/local/bin/helper

CMD ["helper"]
