FROM node:14-buster AS api-builder
ARG VUE_APP_BASE_URL
ENV VUE_APP_BASE_URL $VUE_APP_BASE_URL
WORKDIR /srv
COPY client/dev/describo-online/ui/ /srv/
COPY client/dev/describo-ui-plugins/ /plugins/
RUN npm install
RUN npm run build

FROM nginx:latest
COPY setup/nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=api-builder /srv/dist/ /usr/share/nginx/html
