FROM node:14-alpine3.10 AS web
WORKDIR /app
COPY client/dev/web/package.json client/dev/web/yarn.lock ./
RUN yarn install
COPY client/dev/web /app
RUN yarn build

FROM nginx:latest

COPY --from=web /app/dist /usr/share/nginx/html
